### ISSUE TITLE
Can't send test notification

### ISSUE THREAD

**Issue by jaredallard** [jellyfin/jellyfin-plugin-slack#3]
Error in logs:

```c#
[04:49:36] [ERR] Error processing request
System.InvalidOperationException: Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
   at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.AddRequestHeaders(HttpRequestMessage request, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.GetRequestMessage(HttpRequestOptions options, HttpMethod method)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Jellyfin.Plugin.Slack.Api.ServerApiEndpoints.Post(TestNotification request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

Happens when I click "test notification" after saving an incoming webhook URL.

**Comment by anthonylavado** [comment]
Is this with Jellyfin 10.3.7? If so, we may have missed updating this.

**Comment by jaredallard** [comment]
@anthonylavado Yep it is, forgot to put the version oops!
